sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1999csysh

  minio:
    endpoint: http://127.0.0.1:9000
    access-key: 2vL1sR4EYDCV9XjwixZI
    secret-key: LwPSIuHceJXB6XTkuE6KTBaaFvJsepD1LuDuFiwI
    bucket-name: sky
